version: '3.7'
services:
  blogie_service:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./scripts/sql/blogie.sql:/data/application/init.sql
    container_name: blogie
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=blogie
      - MYSQL_USER=root
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14269:14268"
      - "9411:9411"
