# Server config
Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
  HeaderBytes: 1048576

# Application config
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8080/static
  UploadImageMaxSize: 5
  UploadImageAllowExts:
    - .jpg
    - .png
  ContextTimeout: 60

# Database config
Database:
  DBType: mysql
  Username: root
  Password: 
  Host: 127.0.0.1:3306
  DBName: blogie
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

# Redis cache
Redis:
  Host: 127.0.0.1:6379
  Password:
  MaxIdle: 30
  MaxActive: 30
  IdelTimeout: 200

# JWT config
JWT:
  Secret: i0Ek3
  Issuer: blogie
  Expire: 7200

# Email config
Email:
  Host: smtp.qq.com
  Port: 465
  UserName:
  Password:
  IsSSL: True
  From:
  To:

# Global Enable config
Enable:
  Enable: False
  Debug: True
